name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Run all tests with extended timeouts
      working-directory: playwright-in-java-sample-code-sample-code-module-16-allure-reporting
      run: mvn clean test -f pom-ci.xml -Dplaywright.timeout=120000 -Dplaywright.actionTimeout=60000
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          playwright-in-java-sample-code-sample-code-module-16-allure-reporting/target/surefire-reports/
          playwright-in-java-sample-code-sample-code-module-16-allure-reporting/target/allure-results/
        if-no-files-found: warn
          
    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: playwright-in-java-sample-code-sample-code-module-16-allure-reporting/target/allure-results
        allure_history: allure-history
        gh_pages: gh-pages
        report_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}